DROP TABLE IF EXISTS projects;

CREATE TABLE projects (
	ID SERIAL PRIMARY KEY NOT NULL,
	TITLE VARCHAR NOT NULL,
	DESCRIPTION VARCHAR NOT NULL,
	SKILLS VARCHAR NOT NULL,
	WEBSITE VARCHAR NOT NULL,
	PHOTO_FILE_NAME VARCHAR NOT NULL 
)

